from pydantic import BaseModel, Field

from schemas.generated_file import GeneratedFile


class BackendProject(BaseModel):
    """
    Complete backend generated by the Backend Engineer.
    """

    project_name: str = Field(
        description="Backend project name."
    )

    description: str = Field(
        description="Short description of the backend."
    )

    files: list[GeneratedFile] = Field(
        default_factory=list,
        description="Every source file required for the backend."
    )