from pydantic import BaseModel, Field


class DatabaseDesign(BaseModel):
    """
    Complete database design generated by the
    Database Engineer Agent.
    """

    database_type: str = Field(
        description="Database technology to use."
    )

    collections: list[str] = Field(
        default_factory=list,
        description="Collections/Tables required."
    )

    relationships: list[str] = Field(
        default_factory=list,
        description="Relationships between collections."
    )

    indexes: list[str] = Field(
        default_factory=list,
        description="Recommended indexes."
    )

    validation_rules: list[str] = Field(
        default_factory=list,
        description="Validation rules."
    )

    mongoose_models: list[str] = Field(
        default_factory=list,
        description="Mongoose models to generate."
    )

    api_dependencies: list[str] = Field(
        default_factory=list,
        description="Collections used by APIs."
    )