from pydantic import BaseModel, Field

from schemas.generated_file import GeneratedFile


class FrontendProject(BaseModel):
    """
    Complete React frontend generated by the Frontend Engineer.
    """

    project_name: str = Field(
        description="Frontend project name."
    )

    description: str = Field(
        description="Short description of the frontend."
    )

    files: list[GeneratedFile] = Field(
        default_factory=list,
        description="Every source file required for the frontend."
    )