from pydantic import BaseModel, Field


class UIDesign(BaseModel):
    """
    Represents the complete UI/UX design specification
    generated by the UI Designer Agent.
    """

    design_vision: str = Field(
        description="Overall UI/UX vision of the application."
    )

    color_palette: list[str] = Field(
        default_factory=list,
        description="Primary and secondary colors."
    )

    typography: list[str] = Field(
        default_factory=list,
        description="Fonts used in the application."
    )

    screens: list[str] = Field(
        default_factory=list,
        description="List of application screens."
    )

    navigation_flow: list[str] = Field(
        default_factory=list,
        description="Navigation between screens."
    )

    components: list[str] = Field(
        default_factory=list,
        description="Reusable UI components."
    )

    responsiveness: list[str] = Field(
        default_factory=list,
        description="Responsive design guidelines."
    )

    accessibility: list[str] = Field(
        default_factory=list,
        description="Accessibility recommendations."
    )

    animations: list[str] = Field(
        default_factory=list,
        description="Recommended animations."
    )